<%@ page contentType="text/html; charset=UTF-8" %>
<%@ taglib prefix="s" uri="/struts-tags" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
<div class="td-header-wrap td-header-style-1">

    <div class="td-header-top-menu-full">
        <div class="td-container td-header-row td-header-top-menu">
            <div class="top-bar-style-2">
                <div class="td-header-sp-top-menu">
                    <div class="td_data_time">星期三, 十一月 9日, 2016.</div>
                    <div class="menu-top-container">
                        <ul id="menu-td-demo-top-menu" class="top-header-menu">
                            <li id="menu-item-33"
                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-first td-menu-item td-normal-menu menu-item-33">
                                <a href="http://www.ladichan.com/?page_id=30">联系我们</a></li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="td-banner-wrap-full td-logo-wrap-full">
        <div class="td-container td-header-row td-header-header">
            <div class="td-header-sp-logo">
                <a href="http://www.ladichan.com/">
                    <img class="td-retina-data"
                         src="/images/dwgy_logo.png" alt=""/>
                </a>
            </div>
            <div class="td-header-sp-recs">
                <div class="td-header-rec-wrap">

                    <!-- A generated by theme -->

                    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>


                    <!-- end A -->


                </div>
            </div>
        </div>
    </div>

    <div class="td-header-menu-wrap-full">
        <div class="td-header-menu-wrap td-header-gradient">
            <div class="td-container td-header-row td-header-main-menu">
                <div id="td-header-menu">
                    <div id="td-top-mobile-toggle"><a href="#"><i class="td-icon-font td-icon-mobile"></i></a>
                    </div>
                    <div class="td-main-menu-logo">
                        <a href="http://www.ladichan.com/">
                            <img class="td-retina-data"
                                 data-retina="http://www.ladichan.com/wp-content/uploads/2016/02/ladichan-logo-2.png"
                                 src="http://www.ladichan.com/wp-content/uploads/2016/02/ladichan-logo-2.png"
                                 alt=""/>
                        </a>
                    </div>
                    <div class="menu-main-nav-container">
                        <ul id="menu-main-nav-1" class="sf-menu">
                            <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-first td-menu-item td-normal-menu menu-item-154">
                                <a href="main">首页</a></li>
                            <li class="menu-item menu-item-type-taxonomy menu-item-object-category td-menu-item td-normal-menu menu-item-421">
                                <a href="vancities">热门城市</a></li>
                            <li class="menu-item menu-item-type-taxonomy menu-item-object-category td-menu-item td-normal-menu menu-item-150">
                                <a href="http://www.ladichan.com/?cat=21">楼花转让</a></li>
                            <li class="menu-item menu-item-type-taxonomy menu-item-object-category td-menu-item td-normal-menu menu-item-151">
                                <a href="http://www.ladichan.com/?cat=19">房产分析</a></li>
                            <li class="menu-item menu-item-type-taxonomy menu-item-object-category td-menu-item td-normal-menu menu-item-153">
                                <a href="http://www.ladichan.com/?cat=20">购房指南</a></li>
                            <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children td-menu-item td-normal-menu menu-item-516">
                                <a>常用工具</a>
                                <ul class="sub-menu">
                                    <li class="menu-item menu-item-type-post_type menu-item-object-page td-menu-item td-normal-menu menu-item-518">
                                        <a href="morgagecalculate">房屋贷款计算器</a></li>
                                    <li class="menu-item menu-item-type-post_type menu-item-object-page td-menu-item td-normal-menu menu-item-1042">
                                        <a href="realestateterm">地产词典</a></li>
                                </ul>
                            </li>
                            <li class="menu-item menu-item-type-taxonomy menu-item-object-category td-menu-item td-normal-menu menu-item-421">
                                <a href="list">后台管理</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
