<%@ page contentType="text/html; charset=UTF-8" %>
<%@ taglib prefix="s" uri="/struts-tags" %>

<div class="td-header-wrap td-header-style-1">
    <div class="td-header-top-menu-full">
        <div class="td-container td-header-row td-header-top-menu">
            <div class="top-bar-style-2">
                <div class="td-header-sp-top-menu">
                    <div class="td_data_time" id="current_date"></div>
                    <div class="td_data_time">
                        <a href="main"><s:text name="header.contact"/></a>
                    </div>
                    <s:set var="lang" value="locale.language"/>
                    <div class="td_data_time">
                        <s:if test="#lang=='zh'">
                            <a id="language" href="#">English</a>
                        </s:if>
                        <s:else>
                            <a id="language" href="#">中国（简体）</a>
                        </s:else>
                    </div>
                    <div class="td_data_time">
                        <s:if test="#session['log_in_user_key']==null">
                            <button class="btn btn-primary" data-toggle="modal" data-target="#loginFormModaldialog">
                                <s:text name="header.loginsignup"/>
                            </button>
                        </s:if>
                        <s:else>
                            <li class="dropdown list-unstyled">
                                <a href="#" class="btn btn-primary" data-toggle="dropdown"
                                   aria-haspopup="true" aria-expanded="false">
                                    Hi, <s:property value="#session.log_in_user_key.firstName"/>&nbsp;<s:property
                                        value="#session.log_in_user_key.lastName"/>
                                    &#9660;

                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="loadAccount"><s:text name="header.account"/></a></li>
                                    <li><a id="logout" href="javascript:logoutfunc();"><s:text
                                            name="header.logout"/></a></li>
                                </ul>
                            </li>
                        </s:else>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="td-banner-wrap-full td-logo-wrap-full">
        <div class="td-container td-header-row td-header-header">
            <div class="td-header-sp-logo">
                <a href="http://www.ladichan.com/">
                    <img class="td-retina-data"
                         src="/images/dwgy_logo.png" alt=""/>
                </a>
            </div>
            <div class="td-header-sp-recs">
                <div class="td-header-rec-wrap">

                    <!-- A generated by theme -->

                    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>


                    <!-- end A -->


                </div>
            </div>
        </div>
    </div>

    <nav class="navbar navbar-kootour nomargin">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#navbar-kootour-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!--<a class="navbar-brand navbar-brand-img" href="index.html">
                    <img  alt="Brand" src="/images/icons/logo.svg" />
                </a>  -->
                <p class="navbar-text kootour-link">
                    <a href="#">TAOFUN</a>
                </p>
            </div>

            <div class="collapse navbar-collapse" id="navbar-kootour-collapse">
                <ul class="nav navbar-nav">
                    <li><a class="is-active" href="main"><s:text name="header.main"/></a></li>
                    <li><a href="/vancities"><s:text name="header.cities"/></a></li>
                    <li class="dropdown">
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle"><s:text name="header.tool"/><b
                                class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="morgagecalculate"><s:text name="header.calc"/></a></li>
                            <li><a href="realestateterm"><s:text name="header.term"/></a></li>
                           <!-- <li class="divider"></li>
                            <li><a href="#">Trash</a></li> -->
                        </ul>
                    </li>

                    <s:if test="#session['log_in_user_key']!=null">
                        <li class="dropdown">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle"><s:text name="header.management"/><b
                                    class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a class="" href="/list"><s:text name="header.list"/></a></li>
                                <li><a class="" href="/list"><s:text name="header.list"/></a></li>
                            </ul>
                        </li>
                    </s:if>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div>
    </nav>
    <s:if test="#session['log_in_user_key']==null">
        <div class="modal modal--rew fade registrationform modalform" id="loginFormModaldialog" tabindex="-1"
             role="dialog"
             aria-labelledby="myLargeModalLabel"
             aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="col-lg-12 col-md-112 col-sm-12 col-xs-12">
                        <section class="section">
                            <div class="modal-header">
                                <button type="button" class="close" id="closeModal" data-dismiss="modal"
                                        aria-hidden="true">
                                    ×
                                </button>
                                <div class="login-wrap">
                                    <div class="login-container">
                                        <p class="nomargin text-right blue"><b><s:text name="header.login"/></b></p>
                                    </div>
                                    <div class="login-separator">
                                        <p class="nomargin text-center blue">|</p>
                                    </div>
                                    <div class="login-container">
                                        <p class="nomargin text-left blue"><s:text name="header.signup"/></p>
                                    </div>
                                </div>

                                <div class="login-wrap login-wrap-collapse">
                                    <div class="login-container">
                                        <a class="btn btn-social fullwidth btn-social-facebook">
                                            <img alt="Brand" src="/images/icons/facebook_signup.png"/> facebook
                                        </a>
                                    </div>
                                    <div class="login-separator"></div>
                                    <div class="login-container">
                                        <a class="btn btn-social fullwidth btn-social-wechat">
                                            <img alt="Brand" src="/images/icons/wechat.png"/> wechat
                                        </a>
                                    </div>
                                </div>

                                <div class="login-wrap">
                                    <div class="login-container"></div>
                                    <div class="login-separator">
                                        <p class="nomargin text-center blue">OR</p>
                                    </div>
                                    <div class="login-container"></div>
                                </div>
                            </div>
                            <div class="modal-body" style="border-style: none;">
                                <div class="row">
                                    <div class="col-md-12">
                                        <!-- Nav tabs -->
                                        <ul class="nav nav-tabs">
                                            <li class="active"><a href="#Login" data-toggle="tab"><s:text
                                                    name="header.login"/></a></li>
                                            <li><a href="#signup" data-toggle="tab"><s:text name="header.signup"/></a>
                                            </li>
                                        </ul>
                                        <!-- Tab panes -->
                                        <div class="tab-content">
                                            <!-- Tab for Log In-->
                                            <div class="tab-pane active" id="Login">
                                                <form method="post" id="login_form" novalidate="novalidate"
                                                      class="form-horizontal">
                                                    <div class="form-group">
                                                        <div id="login_error" style="color:red"></div>
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="loginemail" class="col-sm-2 taofun-main-color">
                                                            <s:text name="header.email"/></label>
                                                        <div class="col-sm-10">
                                                            <div class="form-validator">
                                                                <input type="email"
                                                                       class="form-control input-lg gray"
                                                                       name="loginemail"
                                                                       id="loginemail" placeholder="Email">
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="loginpassword" class="col-sm-2 taofun-main-color">
                                                            <s:text name="header.password"/></label>
                                                        <div class="col-sm-10 ">
                                                            <div class="form-validator">
                                                                <input type="password"
                                                                       class="form-control input-lg gray"
                                                                       name="loginpassword"
                                                                       id="loginpassword" placeholder="Password">
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                        <div class="checkbox col-sm-offset-2 col-sm-10">
                                                            <label class="taofun-main-color_no_padding">
                                                                <input type="checkbox"> <s:text
                                                                    name="header.rememberme"/>
                                                            </label>
                                                        </div>
                                                    </div>

                                                    <div class="form-group">
                                                        <a href="forget-password.html" role="button"><s:text
                                                                name="header.forgetpassword"/></a>
                                                    </div>
                                                    <button type="submit"
                                                            class="btn btn-kootour-bold fullwidth"><s:text
                                                            name="header.login"/>
                                                    </button>

                                                </form>
                                            </div>

                                            <!-- Tab for Sign Up-->
                                            <div class="tab-pane" id="signup">
                                                <form method="post" id="reg_form" novalidate="novalidate"
                                                      class="form-horizontal">
                                                    <div class="form-group">
                                                        <div id="signup_error" style="color:red"></div>
                                                    </div>
                                                    <div class="form-group">
                                                        <label class="col-sm-2 taofun-main-color">
                                                            <s:text name="header.name"/></label>
                                                        <div class="col-sm-10">
                                                            <div class="form-validator col-md-6">
                                                                <input type="text"
                                                                       class="form-control  input-lg gray"
                                                                       name="firstname"
                                                                       id="firstname" placeholder="First Name"/>
                                                            </div>
                                                            <div class="form-validator col-md-6">
                                                                <input type="text"
                                                                       class="form-control  input-lg gray"
                                                                       name="lastname"
                                                                       id="lastname" placeholder="Last Name"/>

                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="signupemail" class="col-sm-2 taofun-main-color">
                                                            <s:text name="header.email"/></label>
                                                        <div class="col-sm-10">
                                                            <div class="form-validator">
                                                                <input type="email"
                                                                       class="form-control input-lg gray"
                                                                       name="signupemail"
                                                                       id="signupemail" placeholder="Email">
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="signuppassword" class="col-sm-2 taofun-main-color">
                                                            <s:text name="header.password"/></label>
                                                        <div class="col-sm-10 ">
                                                            <div class="form-validator">
                                                                <input type="password"
                                                                       class="form-control input-lg gray"
                                                                       name="signuppassword"
                                                                       id="signuppassword" placeholder="Password">
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div class="form-group">
                                                        <label for="resignuppassword"
                                                               class="col-sm-2 taofun-main-color">
                                                            <s:text name="header.repassword"/></label>
                                                        <div class="col-sm-10 ">
                                                            <div class="form-validator">
                                                                <input type="password"
                                                                       class="form-control input-lg gray"
                                                                       name="resignuppassword"
                                                                       id="resignuppassword"
                                                                       placeholder="Re-enter Password"
                                                                       required="required">
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <button type="submit" class="btn btn-kootour-bold fullwidth"><s:text
                                                            name="header.signup"/>
                                                    </button>
                                                    <br>
                                                    <br>
                                                    <button type="submit" class="btn btn-kootour-bold fullwidth"
                                                            onClick="this.form.reset()"><s:text name="header.reset"/>
                                                    </button>
                                                </form>
                                            </div>
                                        </div>

                                    </div>

                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </s:if>
</div>
<script src="/js/jquery3.1.1.min.js"></script>
<script src="/js/jquery.validate.min.js"></script>
<script src="/js/bootstrap3.3.7.min.js"></script>
<script src="/js/header.js"></script>
<s:if test="#session['log_in_user_key']==null">
    <script src="/js/logininandsignup.js"></script>
</s:if>
